---
#
# Generic Playbook to install collectd on generic machine types, use tags to seperate machine type:
#
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="graphite"
# ansible-playbook --private-key conf/id_rsa -i conf/hosts.ini playbooks/monitoring/collectd-generic.yaml --tags="gluster34"
- hosts: gluster
  remote_user: root
  vars:
    config_type: gluster
  vars_files:
    - ../conf/glustermon.yaml
  roles:
    - collectd-generic
  tags: gluster34

